packages:
  - apps/*
  - packages/*
  - packages/core/*

catalog:
  "@apollo/datasource-rest": 6.4.1
  "@apollo/server": 5.2.0
  "@apollo/utils.keyvadapter": ^4.0.1
  "@apollo/utils.keyvaluecache": ^4.0.0
  "@faker-js/faker": 10.1.0
  "@kubb/cli": 4.20.1
  "@kubb/core": 4.20.1
  "@kubb/plugin-faker": 4.20.1
  "@kubb/plugin-msw": 4.37.5
  "@kubb/plugin-oas": 4.20.1
  "@kubb/plugin-ts": 4.20.1
  "@kubb/plugin-zod": 4.20.1
  "@mikro-orm/cli": ^7.0.12
  "@mikro-orm/core": ^7.0.12
  "@mikro-orm/decorators": ^7.0.12
  "@mikro-orm/migrations": ^7.0.12
  "@mikro-orm/postgresql": ^7.0.12
  "@mikro-orm/reflection": ^7.0.12
  "@mikro-orm/seeder": ^7.0.12
  "@mikro-orm/sqlite": ^7.0.12
  "@types/luxon": ^3.7.1
  "@types/node": ^24.0.0
  "@typescript-eslint/parser": ^8.49.0
  "@vitest/coverage-v8": ^4.1.1
  bullmq: ^5.71.0
  bullmq-otel: ^1.2.0
  class-validator: 0.14.3
  dedent: ^1.7.1
  discord-api-types: 0.38.42
  es-toolkit: ^1.44.0
  eslint: ^9.39.2
  graphql: 16.12.0
  graphql-scalars: ^1.25.0
  graphql-tag: ^2.12.6
  jiti: 2.6.1
  luxon: ^3.7.2
  msw: 2.13.2
  redis-memory-server: ^0.16.0
  reflect-metadata: 0.2.2
  type-graphql: 2.0.0-rc.2
  typescript: ^5.9.3
  undici: ^7.18.2
  vitest: ^4.1.1
  winston: ^3.19.0
  xstate: ^5.25.0
  zod: ^4.3.6
  zod-validation-error: ^5.0.0
  zod2md: ^0.2.5

catalogMode: prefer

cleanupUnusedCatalogs: true

engineStrict: true

forceLegacyDeploy: true

ignoredBuiltDependencies:
  - redis-memory-server

linkWorkspacePackages: true

nodeVersion: 24.15.0

onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@parcel/watcher"
  - "@swc/core"
  - "@zkochan/fuse-native"
  - better-sqlite3
  - core-js-pure
  - cpu-features
  - es5-ext
  - esbuild
  - msgpackr-extract
  - msw
  - protobufjs
  - sqlite3
  - ssh2
  - unrs-resolver

packageExtensions:
  "@opentelemetry/sdk-node":
    dependencies:
      "@opentelemetry/context-async-hooks": ^2.0.0
  "@zkochan/fuse-native@*":
    dependencies:
      node-gyp: ^12.0.0
  "@zkochan/fuse-shared-library@*":
    dependencies:
      fuse-shared-library-linux-arm64: github:runkit-forks/fuse-shared-library-linux-arm64#11e96e0745fd800ea3e0a4c8cc3b57fceba461cb
  bullmq-otel:
    dependencies:
      tslib: ^2.0.0
patchedDependencies:
  "@zkochan/fuse-shared-library": patches/@zkochan__fuse-shared-library.patch

publicHoistPattern:
  - "*vitest*"
  - vite-node

useNodeVersion: 24.15.0
